import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
const SB=Deno.env.get('SUPABASE_URL')!;const SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const ANON=Deno.env.get('SUPABASE_ANON_KEY')||'';
const C={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type, x-request-id','Access-Control-Allow-Methods':'POST, OPTIONS'};
const J=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...C,'Content-Type':'application/json','Cache-Control':'no-store'}});
async function db(p:string,i:RequestInit={}){const h=new Headers(i.headers||{});h.set('apikey',SERVICE);h.set('Authorization',`Bearer ${SERVICE}`);h.set('Content-Type','application/json');const r=await fetch(SB+p,{...i,headers:h});const t=await r.text();let d:any=null;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw new Error(`DB_${r.status}`);return d}
async function auth(a:string){const r=await fetch(SB+'/auth/v1/user',{headers:{apikey:ANON,Authorization:a}});return r.ok?r.json():null}
function route(m:string,role:string){const q=m.toLowerCase();const rules:[string,string[]][]=[['scholarship',['scholarship','grant']],['career',['career','cv','resume','interview']],['job',['job','vacancy','employment']],['marketing',['marketing','campaign','advertising']],['finance',['finance','revenue','budget']],['technology',['code','bug','technical']],['teacher',['lesson','quiz','exam','teaching']],['student',['explain','homework','study']]];for(const [k,w] of rules)if(w.some(x=>q.includes(x)))return k;return role==='teacher'?'teacher':role==='student'?'student':'master'}
function risky(m:string){const q=m.toLowerCase();return ['send ','publish ','delete ','remove ','pay ','transfer ','hire ','fire ','terminate ','refund ','payout ','change security','legal commitment'].some(x=>q.includes(x))}
function requestedTool(m:string){const q=m.toLowerCase();if(/progress|learning progress|my grades|courses completed/.test(q))return'get_student_progress';if(/my profile|who am i|my account/.test(q))return'get_current_user';if(/scholarship|grant/.test(q))return'search_scholarships';if(/job|vacanc|employment|opportunit/.test(q))return'search_jobs';if(/course|learn|training|skill/.test(q))return'search_courses';if(/platform data|mela catalog|catalog/.test(q))return'search_platform_data';if(/report|generate.*report/.test(q))return'generate_report';return null}
async function execute(a:string,taskId:string){const r=await fetch(SB+'/functions/v1/mela-ai-execution-v2',{method:'POST',headers:{'Content-Type':'application/json','Authorization':a,'apikey':ANON,'x-request-id':crypto.randomUUID()},body:JSON.stringify({task_id:taskId})});const t=await r.text();let d:any={};try{d=t?JSON.parse(t):{}}catch{d={error:t}}return{ok:r.ok,status:r.status,data:d}}
async function createApproval(uid:string,agent:any,message:string,tool:string|null){const existing=(await db(`/rest/v1/mela_ai_approvals?select=id,task_id,action_payload&requested_by=eq.${encodeURIComponent(uid)}&status=eq.pending&order=created_at.desc&limit=20`))?.find((x:any)=>x.action_payload?.request===message&&x.action_payload?.tool===(tool||null));if(existing?.task_id)return existing.task_id;const task=(await db('/rest/v1/mela_ai_tasks',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({created_by:uid,assigned_agent_id:agent.id,title:'Approval required: '+message.slice(0,140),description:message,priority:4,approval_level:2,status:'waiting_approval',approval_status:'pending',retry_count:0,max_retries:2,verification_status:'pending'})}))?.[0];if(!task?.id)throw new Error('TASK_CREATE_FAILED');await db('/rest/v1/mela_ai_approvals',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({task_id:task.id,requested_by:uid,level:2,action_type:tool||'high_impact_action',action_payload:{request:message,tool}})});return task.id}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:C});if(req.method!=='POST')return J({error:'Method not allowed'},405);try{const a=req.headers.get('Authorization')||'';if(!a.startsWith('Bearer '))return J({error:'Authentication required'},401);const u=await auth(a);if(!u?.id)return J({error:'Invalid session'},401);const b=await req.json().catch(()=>({}));const message=String(b.message||'').trim().slice(0,6000);if(!message)return J({error:'Message is required'},400);const prof=(await db(`/rest/v1/profiles?select=id,role,full_name&id=eq.${u.id}&limit=1`))?.[0];if(!prof?.role)return J({error:'User role is not configured'},403);const agentKey=route(message,String(prof.role));const toolKey=requestedTool(message);if(toolKey==='search_scholarships')return J({error:'This workflow is outside the launch scope and is disabled.'},409);if(toolKey==='generate_report')return J({error:'Report generation is restricted to administrators.'},403);const agent=(await db(`/rest/v1/mela_ai_agents?select=id,agent_key,name,domain&agent_key=eq.${encodeURIComponent(agentKey)}&enabled=eq.true&limit=1`))?.[0];if(!agent)return J({error:'No enabled agent is available for this request'},503);if(risky(message)){const taskId=await createApproval(u.id,agent,message,toolKey);return J({ok:true,mode:'approval',task_id:taskId,agent:{key:agent.agent_key,name:agent.name,domain:agent.domain},tool:toolKey,message:'Approval required before execution.'},202)}const task=(await db('/rest/v1/mela_ai_tasks',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({created_by:u.id,assigned_agent_id:agent.id,title:message.slice(0,140),description:message,priority:3,approval_level:1,status:'queued',approval_status:'not_required',retry_count:0,max_retries:2,verification_status:'pending'})}))?.[0];if(!task?.id)return J({error:'Task creation failed'},500);let result:any=null;let attempts=0;while(attempts<1){attempts++;result=await execute(a,task.id);if(result.ok)break;if(attempts<1)await new Promise(r=>setTimeout(r,250*attempts))}if(!result?.ok)return J({ok:false,mode:'failed',task_id:task.id,attempts,error:'AI execution failed after retries'},502);return J({ok:true,mode:'completed',task_id:task.id,agent:{key:agent.agent_key,name:agent.name,domain:agent.domain},attempts,result:result.data})}catch(e){console.error(e);return J({error:'Coordinator failure',code:'COORDINATOR_ERROR'},500)}});
