import React,{useEffect,useState}from'react';
import{AlertTriangle,Eye,RefreshCw,Search,ShieldCheck,XCircle}from'lucide-react';
import{adminApi}from'../lib/admin-api';
import{cancelInvitationCommission,listInvitationCommissions,type InvitationCommission}from'../lib/invitation-commission';
import type{SupabaseClient}from'@supabase/supabase-js';

export default function InvitationCommissionControl({supabase}:{supabase:SupabaseClient}){
 const[rows,setRows]=useState<InvitationCommission[]>([]),[status,setStatus]=useState(''),[search,setSearch]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[selected,setSelected]=useState<InvitationCommission|null>(null),[reason,setReason]=useState(''),[confirm,setConfirm]=useState(false),[stats,setStats]=useState<any>(null);
 const load=async()=>{setBusy(true);setError('');try{const[r,s]=await Promise.all([listInvitationCommissions(supabase,{status:status as any||undefined,search:search||undefined,limit:100}),adminApi(supabase,'commission.summary',{commission_type:'invitation_registration'})]);setRows(r.data??[]);setStats(s)}catch(e:any){setError(e?.message??'Unable to load invitation commissions')}finally{setBusy(false)}};
 useEffect(()=>{void load()},[status]);
 const cancel=async()=>{if(!selected)return;setBusy(true);setError('');try{await cancelInvitationCommission(supabase,selected.id,reason);setConfirm(false);setReason('');setSelected(null);await load()}catch(e:any){setError(e?.message??'Unable to cancel commission')}finally{setBusy(false)}};
 return <section className="panel"><div className="module-head"><div><h2>Invitation Commissions</h2><p>Automatic registration commissions only. Payments are created by the trusted backend; this dashboard provides visibility and administrative control.</p></div><button className="refresh"onClick={()=>void load()}disabled={busy}><RefreshCw size={15}/>{busy?'Syncing':'Sync'}</button></div>
 {error&&<div className="error"><AlertTriangle size={16}/>{error}</div>}
 <div className="grid"><div className="metric"><span>Pending</span><strong>{stats?.pending??'—'}</strong><small>Awaiting payout</small></div><div className="metric"><span>Paid</span><strong>{stats?.paid??'—'}</strong><small>Completed</small></div><div className="metric"><span>Cancelled</span><strong>{stats?.cancelled??'—'}</strong><small>Reversed/blocked</small></div><div className="metric"><span>Total value</span><strong>{stats?.total_amount??'—'}</strong><small>ETB</small></div></div>
 <div className="toolbar"><div className="searchbox"><Search size={17}/><input value={search}placeholder="Search transaction, invitation code or user ID"onChange={e=>setSearch(e.target.value)}onKeyDown={e=>{if(e.key==='Enter')void load()}}/></div><select value={status}onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option value="pending">Pending</option><option value="paid">Paid</option><option value="cancelled">Cancelled</option></select><button className="refresh"onClick={()=>void load()}disabled={busy}>Apply</button></div>
 <div className="table-wrap"><table><thead><tr><th>Transaction</th><th>Inviter</th><th>Registered user</th><th>Amount</th><th>Status</th><th>Created</th><th/></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><strong>{r.transaction_reference}</strong><small>{r.invitation_code||'—'}</small></td><td>{r.inviter_user_id}</td><td>{r.registered_user_id}</td><td>{r.amount} {r.currency}</td><td><span className={`status-pill ${r.status}`}>{r.status}</span></td><td>{new Date(r.created_at).toLocaleString()}</td><td><button className="icon-btn"onClick={()=>setSelected(r)}><Eye size={17}/></button></td></tr>)}{!rows.length&&!busy&&<tr><td colSpan={7}className="empty">No invitation commissions found.</td></tr>}</tbody></table></div>
 {selected&&<div className="detail-card"><div className="module-head"><div><h3>Commission details</h3><p>{selected.transaction_reference}</p></div><button className="icon-btn"onClick={()=>setSelected(null)}><XCircle size={18}/></button></div><dl><dt>Inviter</dt><dd>{selected.inviter_user_id}</dd><dt>Registered user</dt><dd>{selected.registered_user_id}</dd><dt>Invitation code</dt><dd>{selected.invitation_code||'—'}</dd><dt>Amount</dt><dd>{selected.amount} {selected.currency}</dd><dt>Status</dt><dd>{selected.status}</dd><dt>Eligibility</dt><dd>{selected.eligibility_reason||'—'}</dd></dl>{selected.status==='pending'&&<><div className="notice"><ShieldCheck size={18}/><span>Cancellation is irreversible for this commission state and will be recorded in the audit trail.</span></div><button className="refresh"onClick={()=>setConfirm(true)}disabled={busy}><XCircle size={15}/>Cancel commission</button></>}{confirm&&<div className="detail-card"><h3>Confirm cancellation</h3><p>Provide a reason. The financial record will remain; it will not be deleted.</p><textarea value={reason}onChange={e=>setReason(e.target.value)}maxLength={500}placeholder="Reason for cancellation"style={{width:'100%',minHeight:100,boxSizing:'border-box',background:'#0a1120',color:'#fff',border:'1px solid #2b3855',borderRadius:10,padding:12}}/><div className="toolbar"><button className="refresh"onClick={()=>setConfirm(false)}>Keep</button><button className="refresh"onClick={()=>void cancel()}disabled={busy||reason.trim().length<5}>{busy?'Cancelling…':'Confirm cancellation'}</button></div></div>}</div>}
 </section>
}
