import React, { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { type Session, type User } from '@supabase/supabase-js'
import { ShieldCheck, LayoutDashboard, Users, LockKeyhole, FileClock, Settings, LogOut, AlertTriangle, RefreshCw, BriefcaseBusiness, CreditCard, Gavel, Radio } from 'lucide-react'
import './styles.css'
import { createAdminClient, getAdminMe, adminApi } from './lib/admin-api'

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL as string | undefined
const supabaseKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined
const supabase = supabaseUrl && supabaseKey ? createAdminClient() : null
const nav = [
 {id:'overview',label:'Overview',icon:LayoutDashboard},{id:'users',label:'Users',icon:Users},{id:'opportunities',label:'Opportunities',icon:BriefcaseBusiness},{id:'payments',label:'Payments',icon:CreditCard},{id:'disputes',label:'Disputes',icon:Gavel},{id:'moderation',label:'Moderation',icon:Radio},{id:'access',label:'Authorization',icon:LockKeyhole},{id:'audit',label:'Audit Log',icon:FileClock},{id:'settings',label:'System',icon:Settings}
] as const
type Section=typeof nav[number]['id']
type AdminState={allowed:boolean;role?:{key:string;name:string};permissions:string[];mfaVerified:boolean}
type OverviewData={metrics:any;system:any;features:any[];queues:any}
function App(){const[session,setSession]=useState<Session|null>(null),[user,setUser]=useState<User|null>(null),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false),[section,setSection]=useState<Section>('overview'),[admin,setAdmin]=useState<AdminState|null>(null),[mfaCode,setMfaCode]=useState(''),[mfaFactorId,setMfaFactorId]=useState<string|null>(null);useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data})=>{setSession(data.session);setUser(data.session?.user??null)});const{data:l}=supabase.auth.onAuthStateChange((_e,n)=>{setSession(n);setUser(n?.user??null)});return()=>l.subscription.unsubscribe()},[]);const loadAdmin=async()=>{if(!session||!supabase){setAdmin(null);return}try{const{data:a}=await supabase.auth.mfa.getAuthenticatorAssuranceLevel();if(a?.currentLevel!=='aal2'){const{data:f}=await supabase.auth.mfa.listFactors();setMfaFactorId(f?.totp?.find((x:any)=>x.status==='verified')?.id??null)}else setMfaFactorId(null);const r=await getAdminMe(supabase);setAdmin({allowed:true,role:r.role,permissions:r.permissions??[],mfaVerified:r.mfa?.currentLevel==='aal2'})}catch(e:any){setAdmin({allowed:false,permissions:[],mfaVerified:false});if(e?.code!=='MFA_REQUIRED')setError(e?.message??'Admin access denied.')}};useEffect(()=>{void loadAdmin()},[session]);const signIn=async(e:React.FormEvent)=>{e.preventDefault();setError('');setLoading(true);if(!supabase){setError('Admin backend is not configured.');setLoading(false);return}const{error}=await supabase.auth.signInWithPassword({email,password});setLoading(false);if(error)setError(error.message)};const verifyMfa=async()=>{if(!supabase||!mfaFactorId||mfaCode.length<6)return;setError('');setLoading(true);const c=await supabase.auth.mfa.challenge({factorId:mfaFactorId});if(c.error){setError(c.error.message);setLoading(false);return}const r=await supabase.auth.mfa.verify({factorId:mfaFactorId,challengeId:c.data.id,code:mfaCode});setLoading(false);if(r.error)setError(r.error.message);else{setMfaCode('');await loadAdmin()}};const signOut=async()=>{await supabase?.auth.signOut()};if(!supabase)return <SetupScreen/>;if(!session||!user)return <LoginScreen email={email} password={password} setEmail={setEmail} setPassword={setPassword} error={error} loading={loading} onSubmit={signIn}/>;if(!admin?.allowed&&mfaFactorId)return <MfaScreen user={user} code={mfaCode} setCode={setMfaCode} error={error} loading={loading} onVerify={verifyMfa} onSignOut={signOut}/>;if(!admin?.allowed)return <BlockedScreen user={user} onSignOut={signOut}/>;return <Dashboard section={section} setSection={setSection} onSignOut={signOut} role={admin.role?.name??'Administrator'} permissions={admin.permissions}/>} 
function SetupScreen(){return <div className="center"><div className="card setup"><ShieldCheck size={42}/><h1>MELA Central Admin</h1><p>Configure <code>VITE_SUPABASE_URL</code> and <code>VITE_SUPABASE_PUBLISHABLE_KEY</code> in the separate deployment.</p></div></div>}
function LoginScreen(p:{email:string;password:string;setEmail:(v:string)=>void;setPassword:(v:string)=>void;error:string;loading:boolean;onSubmit:(e:React.FormEvent)=>void}){return <div className="center"><form className="card login" onSubmit={p.onSubmit}><div className="brand"><ShieldCheck size={34}/><div><strong>MELA</strong><span>Central Admin</span></div></div><h1>Administrator sign in</h1><p className="muted">Separate administrative entrance. Consumer accounts cannot access this dashboard.</p><label>Email<input type="email" autoComplete="username" value={p.email} onChange={e=>p.setEmail(e.target.value)} required/></label><label>Password<input type="password" autoComplete="current-password" value={p.password} onChange={e=>p.setPassword(e.target.value)} required/></label>{p.error&&<div className="error"><AlertTriangle size={16}/>{p.error}</div>}<button disabled={p.loading}>{p.loading?'Signing in…':'Sign in securely'}</button><small>MFA is required for authorized administrators before privileged access is granted.</small></form></div>}
function MfaScreen({user,code,setCode,error,loading,onVerify,onSignOut}:{user:User;code:string;setCode:(v:string)=>void;error:string;loading:boolean;onVerify:()=>void;onSignOut:()=>void}){return <div className="center"><div className="card login"><div className="brand"><ShieldCheck size={34}/><div><strong>MELA</strong><span>Central Admin</span></div></div><h1>Verify MFA</h1><p className="muted">Enter the current authenticator code for {user.email}.</p><input className="mfa" inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))}/>{error&&<div className="error"><AlertTriangle size={16}/>{error}</div>}<button disabled={loading||code.length<6} onClick={onVerify}>{loading?'Verifying…':'Verify and continue'}</button><button className="secondary" onClick={onSignOut}>Cancel</button></div></div>}
function BlockedScreen({user,onSignOut}:{user:User;onSignOut:()=>void}){return <div className="center"><div className="card blocked"><LockKeyhole size={42}/><h1>Admin access required</h1><p>Your account <strong>{user.email}</strong> is not authorized for MELA Central Admin.</p><p className="muted">The dashboard fails closed. No consumer role is promoted automatically.</p><button onClick={onSignOut}>Sign out</button></div></div>}
function Dashboard({section,setSection,onSignOut,role,permissions}:{section:Section;setSection:(s:Section)=>void;onSignOut:()=>void;role:string;permissions:string[]}){const[data,setData]=useState<OverviewData|null>(null),[busy,setBusy]=useState(false),[loadError,setLoadError]=useState('');const refresh=async()=>{if(!supabase)return;setBusy(true);setLoadError('');try{const[d,q]=await Promise.all([adminApi(supabase,'dashboard'),adminApi(supabase,'queues')]);setData({...d,queues:q})}catch(e:any){setLoadError(e?.message??'Unable to load live admin data')}finally{setBusy(false)}};useEffect(()=>{void refresh()},[]);return <div className="shell"><aside><div className="brand side"><ShieldCheck/><div><strong>MELA</strong><span>Central Admin</span></div></div><nav>{nav.map(item=>{const I=item.icon;return <button key={item.id} className={section===item.id?'active':''} onClick={()=>setSection(item.id)}><I size={18}/>{item.label}</button>})}</nav><div className="admin-role">{role} · {permissions.length} permissions</div><button className="logout" onClick={onSignOut}><LogOut size={18}/>Sign out</button></aside><main><header><div><span className="eyebrow">CONTROL PLANE</span><h1>{nav.find(x=>x.id===section)?.label}</h1></div><div className="status"><span/>MFA-protected admin session <button className="refresh" onClick={refresh} disabled={busy}><RefreshCw size={15}/>{busy?'Syncing':'Sync'}</button></div></header>{loadError&&<div className="error"><AlertTriangle size={16}/>{loadError}</div>}{section==='overview'&&<Overview data={data}/>} {section!=='overview'&&<Placeholder title={nav.find(x=>x.id===section)?.label??''} body={section==='users'?'Search, verify, suspend and inspect users through audited backend actions.':section==='opportunities'?'Approve listings and verify employers through existing backend write paths.':section==='payments'?'Monitor payments, escrow, coins and payouts through audited server actions.':section==='disputes'?'Operate tickets, SLA tracking and dispute resolution workflows.':section==='moderation'?'Review reports, proctoring flags and Arena integrity queues.':section==='access'?'Manage the permission matrix, RLS coverage, access requests and sessions.':section==='audit'?'Inspect administrative activity with actor, target and before/after values.':'Manage feature flags, localization and platform configuration.'}/>}</main></div>}
function Overview({data}:{data:OverviewData|null}){const m=data?.metrics||{},q=data?.queues||{};const count=(x:any)=>Array.isArray(x)?x.length:'—';const roleCounts=Array.isArray(m?.users_by_role)?m.users_by_role:[];return <><div className="notice"><RefreshCw size={18}/><span>Live data is connected to the existing MELA admin backend. Values below come from the shared Supabase platform.</span></div><section className="grid"><div className="metric"><span>Users by role</span><strong>{count(roleCounts)}</strong><small>Role groups returned</small></div><div className="metric"><span>Employer queue</span><strong>{count(q.employer_registrations)}</strong><small>Pending registrations</small></div><div className="metric"><span>Proctor reviews</span><strong>{count(q.proctor_reviews)}</strong><small>Review-required attempts</small></div><div className="metric"><span>Pending payouts</span><strong>{count(q.payouts)}</strong><small>Pending/queued/failed</small></div></section><section className="panel"><h2>Operational queues</h2><div className="checks"><div><BriefcaseBusiness/> Employer registrations: <strong>{count(q.employer_registrations)}</strong></div><div><Users/> Mentor verification: <strong>{count(q.mentor_verifications)}</strong></div><div><AlertTriangle/> Reports: <strong>{count(q.reports)}</strong></div><div><Gavel/> Arena integrity: <strong>{count(q.arena_integrity)}</strong></div><div><CreditCard/> Payout requests: <strong>{count(q.payouts)}</strong></div><div><ShieldCheck/> Feature flags: <strong>{count(data?.features)}</strong></div></div></section><section className="panel"><h2>Security foundation</h2><div className="checks"><div><ShieldCheck/>Separate application</div><div><ShieldCheck/>Fail-closed authorization</div><div><ShieldCheck/>MFA required</div><div><ShieldCheck/>Audited privileged writes</div><div><ShieldCheck/>Shared MELA backend</div><div><ShieldCheck/>No service key in browser</div></div></section></>}
function Placeholder({title,body}:{title:string;body:string}){return <section className="panel"><h2>{title}</h2><p>{body}</p><div className="coming">Module UI is next; backend action surface is already available for this control-plane area.</div></section>}
createRoot(document.getElementById('root')!).render(<App/>)