-- Production-applied longer-deadline official opportunities to keep the launch supply gate durable.
do $migration$
declare
  v_admin uuid;
begin
  select au.user_id into v_admin
  from admin.admin_users au
  join public.profiles p on p.id=au.user_id
  where au.active and p.account_status='active' and p.deleted_at is null
  order by au.user_id limit 1;
  if v_admin is null then raise exception 'active admin registry user required'; end if;

  insert into public.opportunities(
    posted_by,title,description,organization,location,is_remote,external_url,deadline,status,
    organization_name,sector_category,opportunity_type,employment_type_label,stipend_or_reward,
    requirements,verified_source,skills_required,experience_level,education_level,summary,
    work_arrangement,application_method,application_instructions,published_at,source_type,source_url,
    source_verified_at,source_verified_by,source_notes,source_last_checked_at,moderation_status,
    moderation_notes,reviewed_by,reviewed_at
  )
  select v_admin,v.title,v.description,v.organization,v.location,v.is_remote,v.source_url,v.deadline::date,'open',
    v.organization,v.sector::public.launch_category,v.opportunity_type::public.opportunity_type,v.employment_type,
    v.reward,v.requirements,v.verified_source,v.skills,v.experience_level,v.education_level,v.summary,
    v.work_arrangement,'external',v.instructions,now(),'official_external',v.source_url,now(),v_admin,v.source_note,
    now(),'approved','Official source verified for launch catalog.',v_admin,now()
  from (values
    ('Statistics & Monitoring Officer (P-2) — UNICEF Florence #138654','UNICEF evidence and monitoring role supporting mortality, demographic monitoring, reporting and child-survival advocacy.','UNICEF Office of Strategy and Evidence','Florence, Italy',false,'https://jobs.unicef.org/cw/en-us/job/596083/statistics-monitoring-officer-p2-temporary-position-364-days-138654-ose-florence-italy','2026-10-23','Health & Sciences','jobs','P-2 Temporary Position — 364 days','UNICEF P-2 compensation and benefits; see official vacancy',array['Monitoring, statistics, demography or related evidence experience','Professional qualification appropriate to P-2 level','See official vacancy for complete requirements'],'UNICEF Careers',array['Statistics','Monitoring','Demography','Evidence generation'],'Early/mid professional','Professional qualification per UNICEF vacancy','UNICEF evidence and monitoring role supporting global child-survival indicators.','onsite','Apply only through the official UNICEF Careers vacancy.','Official UNICEF Careers vacancy verified with 23 October 2026 deadline.'),
    ('University of Melbourne Graduate Research Scholarship Round — 2027','University of Melbourne graduate research candidature and scholarship round for 2027 commencement; complete applications by 31 October 2026 are considered in Round 1.','University of Melbourne','Melbourne, Australia',false,'https://mdhs.unimelb.edu.au/research/research-training/future-students/when-should-i-apply','2026-10-31','Health & Sciences','scholarships','Graduate research scholarship round','Graduate research scholarship support varies by award and faculty selection',array['Submit a complete eligible graduate research application by the round deadline','Meet candidature and scholarship eligibility requirements','Check discipline-specific requirements'],'University of Melbourne Faculty of Medicine, Dentistry and Health Sciences',array['Research','Academic excellence','Graduate study'],null,'Graduate research / PhD or research Masters','Official 2027 graduate research scholarship round.','onsite','Submit through the official University of Melbourne process.','Official University of Melbourne 2027 timeline verified for 31 October 2026 Round 1.'),
    ('University of Sydney RTP Scholarship — International 2027 Research Period 3/4','University of Sydney Australian Government Research Training Program scholarship route for international higher-degree-by-research applicants.','University of Sydney','Sydney, Australia',false,'https://www.sydney.edu.au/scholarships/australian-government-research-training-program/rtp-international.html','2026-12-18','Education & Social Sciences','scholarships','International graduate research scholarship','RTP and equivalent University research scholarship support; see official scholarship page',array['International applicant for an eligible higher degree by research','Apply for admission and submit required documents','Submit the scholarship application by the applicable deadline'],'University of Sydney Scholarships',array['Research','Academic excellence','Graduate study'],null,'Higher degree by research','Official international RTP scholarship route for later 2027 research periods.','onsite','Follow the official University of Sydney admission and RTP application process.','Official University of Sydney timeline verified with 18 December 2026 deadline for 2027 Research Periods 3 and 4.'),
    ('DAAD Study Scholarships — Master Studies for All Academic Disciplines 2027','DAAD scholarship for eligible Master studies in Germany beginning in 2027.','DAAD — German Academic Exchange Service','Germany',false,'https://www2.daad.de/deutschland/stipendium/datenbank/en/21148-scholarship-database/?daad=1&detail=50026200&intention=&origin=25&page=1&q=&status=&subjectGrps=','2026-11-30','Education & Social Sciences','scholarships','Master study scholarship','DAAD Master-study scholarship support; see official database for current rates and benefits',array['Eligible planned Master study in Germany beginning in 2027','Meet DAAD academic and programme-specific requirements','Submit required documents through the DAAD portal'],'DAAD Scholarship Database',array['Academic excellence','Master study','International study'],null,'Bachelor degree / Master entry','Official DAAD Master-study scholarship call.','onsite','Apply through the official DAAD scholarship portal.','Official DAAD scholarship database verified with 30 November 2026 deadline.'),
    ('DAAD Research Grants in Germany — November 2026 Cycle','DAAD Research Grants in Germany funding cycle with a November 2026 application deadline; applicant-country conditions apply.','DAAD — German Academic Exchange Service','Germany',false,'https://www2.daad.de/deutschland/stipendium/datenbank/en/21148-scholarship-database/?daad=1&detail=57742121&intention=&origin=30&page=2&q=&status=&subjectGrps=','2026-11-16','Education & Social Sciences','scholarships','Research grant','Research grant support under DAAD programme terms; see official database for applicant-specific details',array['Meet programme academic/research eligibility rules','Check applicant-origin and subject-specific conditions','Submit the complete research proposal and documents through the DAAD portal'],'DAAD Scholarship Database',array['Research','Academic excellence','Project planning'],null,'Graduate / doctoral research','Official DAAD research-grant cycle; country-specific eligibility applies.','onsite','Review the official DAAD entry for your applicant country and apply through the DAAD portal.','Official DAAD Research Grants entry verified with 16 November 2026 deadline for the displayed cycle.')
  ) as v(title,description,organization,location,is_remote,source_url,deadline,sector,opportunity_type,employment_type,reward,requirements,verified_source,skills,experience_level,education_level,summary,work_arrangement,instructions,source_note)
  where not exists(select 1 from public.opportunities o where o.source_url=v.source_url);
end
$migration$;
