-- Production-applied launch catalog refresh using current official sources only.
do $migration$
declare
  v_admin uuid;
begin
  select au.user_id into v_admin
  from admin.admin_users au
  join public.profiles p on p.id=au.user_id
  where au.active and p.account_status='active' and p.deleted_at is null
  order by au.user_id limit 1;
  if v_admin is null then raise exception 'active admin registry user required to curate launch opportunities'; end if;

  insert into public.opportunities(
    posted_by,title,description,organization,location,is_remote,external_url,deadline,status,
    organization_name,sector_category,opportunity_type,employment_type_label,stipend_or_reward,
    requirements,verified_source,skills_required,experience_level,education_level,summary,
    work_arrangement,application_method,application_instructions,published_at,source_type,source_url,
    source_verified_at,source_verified_by,source_notes,source_last_checked_at,moderation_status,
    moderation_notes,reviewed_by,reviewed_at
  )
  select
    v_admin,v.title,v.description,v.organization,v.location,v.is_remote,v.source_url,v.deadline::date,'open',
    v.organization,v.sector::public.launch_category,v.opportunity_type::public.opportunity_type,
    v.employment_type,v.reward,v.requirements,v.verified_source,v.skills,v.experience_level,v.education_level,
    v.summary,v.work_arrangement,'external',v.instructions,now(),'official_external',v.source_url,
    now(),v_admin,v.source_note,now(),'approved','Official source verified for launch catalog.',v_admin,now()
  from (values
    ('UBC International Scholars Program — 2027 Entry','International undergraduate scholarship route for 2027 entry; the official UBC admissions calendar lists 15 November 2026 as the International Scholars Program application deadline.','University of British Columbia','Vancouver, Canada',false,'https://you.ubc.ca/applying-ubc/dates-deadlines/','2026-11-15','Education & Social Sciences','scholarships','Undergraduate scholarship','International Scholars Program awards; value varies by scholar and demonstrated need',array['International applicant','Apply to UBC by the scholarship deadline','Meet official International Scholars eligibility requirements'], 'University of British Columbia Undergraduate Programs and Admissions',array['Academic excellence','Leadership','Community impact'],null,'Secondary school / undergraduate entry','Official UBC scholarship route for international students seeking 2027 entry.','onsite','Apply only through the official UBC admissions and International Scholars process.','Official UBC dates/deadlines page verified for the 15 November 2026 deadline.'),
    ('Lester B. Pearson International Scholarship — University of Toronto 2027','University of Toronto scholarship for outstanding international students entering undergraduate study in September 2027; scholarship/document deadline is 6 November 2026.','University of Toronto','Toronto, Canada',false,'https://future.utoronto.ca/pearson-scholarships','2026-11-06','Education & Social Sciences','scholarships','Undergraduate scholarship','Tuition, books, incidental fees and full residence support for four years',array['International student requiring a Canadian study permit','School nomination required','Apply for September 2027 entry'], 'University of Toronto Future Students',array['Academic excellence','Creativity','Leadership','School nomination'],null,'Secondary school / undergraduate entry','Fully supported four-year University of Toronto scholarship for selected international entrants.','onsite','Follow the official nomination, admission and Pearson scholarship application sequence.','Official University of Toronto Pearson Scholarship page verified for the 2026 cycle.'),
    ('EPFL Master Excellence Fellowship — 2027','EPFL Excellence Fellowship for candidates applying to an EPFL Master programme; external applicants must validate the Master application by 15 December.','EPFL','Lausanne, Switzerland',false,'https://www.epfl.ch/education/master/master-excellence-fellowships/how-to-apply/','2026-12-15','Education & Social Sciences','scholarships','Master excellence fellowship','CHF 10,000 per semester for up to four semesters; external candidates also receive a room-reservation benefit',array['Apply to an EPFL Master programme','Select fellowship consideration in the application','Meet EPFL eligibility requirements'], 'EPFL Master Excellence Fellowships',array['Academic excellence','Master study','Motivation'],null,'Bachelor degree / Master entry','Competitive EPFL fellowship supporting excellent Master candidates.','onsite','Apply through the official EPFL Master application.','Official EPFL fellowship application page verified with 15 December deadline.'),
    ('Security Manager (P-4) — UNICEF Ethiopia #107113','UNICEF Ethiopia fixed-term Security Manager role leading strategic security risk management, operations, compliance and emergency preparedness in Addis Ababa; for non-Ethiopian nationals.','UNICEF','Addis Ababa, Ethiopia',false,'https://jobs.unicef.org/en-us/job/595959/security-manager-p4-ft-107113-addis-ababa-ethiopia-esar-for-nonethiopian-nationals-only','2026-10-08','Education & Social Sciences','jobs','P-4 Fixed Term Appointment','UNICEF P-4 compensation and benefits; see official vacancy',array['Non-Ethiopian nationals only','Advanced relevant degree','At least eight years relevant international security experience'], 'UNICEF Careers',array['Security risk management','Emergency preparedness','Stakeholder coordination','Security operations'],'Senior','Advanced degree','Senior UNICEF Ethiopia security leadership role.','onsite','Apply only through UNICEF Careers.','Official UNICEF Careers vacancy verified; closes 8 October 2026 EAT.'),
    ('Health Manager — UNICEF Ethiopia #00046937','UNICEF Ethiopia Health Manager role supporting primary health care, immunization, health systems and health-emergency preparedness and response.','UNICEF','Addis Ababa, Ethiopia',false,'https://jobs.unicef.org/mob/cw/en-us/job/595958/health-manager-immunization-health-systems-and-health-emergencies-p4-ft-00046937-addis-ababa-ethiopia-esar','2026-10-08','Health & Sciences','jobs','P-4 Fixed Term Appointment','UNICEF P-4 compensation and benefits; see official vacancy',array['Senior health-program experience','Immunization, health-systems or emergency expertise','See official vacancy for full requirements'], 'UNICEF Careers',array['Public health','Immunization','Health systems','Emergency preparedness'],'Senior','Advanced professional qualification','Senior health-systems and emergencies role with UNICEF Ethiopia.','onsite','Apply only through UNICEF Careers.','Official UNICEF Careers vacancy verified; closes 8 October 2026 EAT.'),
    ('Social & Behavior Change Specialist (NO-3) — UNICEF Ethiopia #00133327','UNICEF Ethiopia national specialist role leading health social-and-behavior-change and community-engagement work.','UNICEF','Addis Ababa, Ethiopia',false,'https://jobs.unicef.org/en-us/search/?location=ethiopia&search-keyword=','2026-10-05','Health & Sciences','jobs','NO-3 Fixed Term Appointment','UNICEF national officer compensation and benefits; see official vacancy',array['For Ethiopian nationals only','Relevant SBC/community-engagement experience','See official vacancy for full requirements'], 'UNICEF Careers Ethiopia vacancy search',array['Social and behavior change','Community engagement','Public health','Programme leadership'],'Experienced professional','Professional qualification per UNICEF vacancy','UNICEF Ethiopia national specialist opportunity in health-related social and behavior change.','onsite','Apply to vacancy #00133327 through the official UNICEF Ethiopia vacancies page.','Official UNICEF Ethiopia vacancy page verified with 5 October 2026 deadline.'),
    ('Senior Economic & Public Finance Consultant — UNICEF Ethiopia #595328','UNICEF consultancy focused on debt, fiscal adjustment and social-sector financing in Ethiopia using empirical and political-economy analysis.','UNICEF','Addis Ababa, Ethiopia / Remote',true,'https://jobs.unicef.org/en-us/search/?search-keyword=ethiopia','2026-10-11','Business & Finance','jobs','National/International Consultancy — 7.5 months','Consultancy remuneration per UNICEF terms; see official vacancy',array['Senior economics/public-finance expertise','Empirical and political-economy analysis','See official vacancy for full requirements'], 'UNICEF Careers',array['Public finance','Economics','Debt analysis','Policy analysis','Social-sector financing'],'Senior consultant','Advanced economics/public finance expertise','Senior UNICEF consultancy on debt and social-sector financing in Ethiopia.','remote','Apply to vacancy #595328 through UNICEF Careers.','Official UNICEF Careers vacancy verified with 11 October 2026 deadline.'),
    ('Procurement Services Manager (P-4) — UNICEF Supply Division #00021902','UNICEF Supply Division role managing procurement-service business transactions with country offices and partners.','UNICEF','Copenhagen, Denmark',false,'https://jobs.unicef.org/en-us/filter/?location=denmark&search-keyword=','2026-10-31','Manufacturing & Logistics','jobs','P-4 Fixed Term Appointment','UNICEF P-4 compensation and benefits; see official vacancy',array['Senior procurement/supply-chain experience','Partner and transaction management','See official vacancy for full requirements'], 'UNICEF Careers Denmark vacancies',array['Procurement','Supply chain','Partner management','Business transactions'],'Senior','Advanced professional qualification','UNICEF Supply Division procurement-services leadership role.','onsite','Apply to vacancy #00021902 through the official UNICEF Denmark vacancies page.','Official UNICEF Careers Denmark page verified with 31 October 2026 deadline.')
  ) as v(title,description,organization,location,is_remote,source_url,deadline,sector,opportunity_type,employment_type,reward,requirements,verified_source,skills,experience_level,education_level,summary,work_arrangement,instructions,source_note)
  where not exists(select 1 from public.opportunities o where o.source_url=v.source_url);
end
$migration$;
