const cors = {'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Content-Type':'application/json'};
function json(data: unknown,status=200){return new Response(JSON.stringify(data),{status,headers:cors})}
function decodeJwt(token:string){const p=token.split('.')[1];if(!p)throw new Error('Invalid session token');const n=p.replace(/-/g,'+').replace(/_/g,'/');return JSON.parse(atob(n.padEnd(Math.ceil(n.length/4)*4,'=')))}
async function rest(path:string,init:RequestInit={}){const u=Deno.env.get('SUPABASE_URL')!,s=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const h=new Headers(init.headers||{});h.set('apikey',s);h.set('Authorization',`Bearer ${s}`);if(init.body)h.set('Content-Type','application/json');const r=await fetch(`${u}/rest/v1/${path}`,{...init,headers:h});const tx=await r.text();let d:any=null;try{d=tx?JSON.parse(tx):null}catch{d=tx}if(!r.ok)throw new Error(typeof d==='object'?(d?.message||d?.hint||`Database error ${r.status}`):`Database error ${r.status}`);return d}
async function updatePayment(id:string,body:any){return rest(`payments?id=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify(body)})}
async function ensureEnrollment(p:any){return rest('course_enrollments',{method:'POST',headers:{Prefer:'resolution=ignore-duplicates,return=minimal'},body:JSON.stringify({user_id:p.user_id,course_id:p.course_id})})}
async function verifyWithChapa(p:any){const key=Deno.env.get('CHAPA_SECRET_KEY');if(!key)throw Object.assign(new Error('Chapa test secret is not configured on the server.'),{code:'CHAPA_NOT_CONFIGURED',status:503});if(!/TEST/i.test(key))throw Object.assign(new Error('This staging endpoint accepts only a Chapa TEST secret key.'),{code:'CHAPA_TEST_KEY_REQUIRED',status:503});const r=await fetch(`https://api.chapa.co/v1/transaction/verify/${encodeURIComponent(p.tx_ref)}`,{headers:{Authorization:`Bearer ${key}`}});const tx=await r.text();let b:any={};try{b=tx?JSON.parse(tx):{}}catch{}const now=new Date().toISOString();if(!r.ok){await updatePayment(p.id,{status:r.status===404?'pending':p.status,provider_status:b?.status||'pending',failure_reason:b?.message||`Chapa verify HTTP ${r.status}`,last_verified_at:now});return{state:r.status===404?'pending':'error',provider:b}}
 const d=b?.data||{};const providerStatus=String(d.status||'').toLowerCase();if(providerStatus!=='success'){const mapped=providerStatus==='failed'?'failed':'pending';await updatePayment(p.id,{status:mapped,provider_status:providerStatus||mapped,verify_payload:b,failure_reason:mapped==='failed'?(b?.message||'Payment failed'):null,last_verified_at:now});return{state:mapped}}
 const cents=Math.round(Number(d.amount)*100);const checks={tx_ref:String(d.tx_ref||'')===p.tx_ref,amount:Number.isFinite(cents)&&cents===Number(p.expected_amount_cents),currency:String(d.currency||'').toUpperCase()===String(p.expected_currency||'').toUpperCase(),mode:String(d.mode||'').toLowerCase()==='test'};if(!Object.values(checks).every(Boolean)){await updatePayment(p.id,{status:'failed',provider_status:providerStatus,verify_payload:b,failure_reason:`Verification mismatch: ${JSON.stringify(checks)}`,last_verified_at:now});return{state:'mismatch',checks}}
 await updatePayment(p.id,{status:'success',provider_status:providerStatus,provider_ref:d.reference||d.ref_id||null,provider_method:d.method||null,provider_type:d.type||null,provider_charge:d.charge??null,verify_payload:b,failure_reason:null,paid_at:p.paid_at||now,last_verified_at:now});await ensureEnrollment(p);return{state:'success'}}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({error:'Method not allowed'},405);try{const token=(req.headers.get('Authorization')||'').replace(/^Bearer\s+/i,'');const uid=decodeJwt(token).sub;if(!uid)return json({error:'Invalid user session'},401);const body=await req.json().catch(()=>({}));const ref=String(body?.tx_ref||'').trim();if(!ref)return json({error:'tx_ref is required'},400);const rows=await rest(`payments?select=*&tx_ref=eq.${encodeURIComponent(ref)}&user_id=eq.${uid}&limit=1`);const p=rows?.[0];if(!p)return json({error:'Payment not found'},404);if(p.status==='success'){await ensureEnrollment(p);return json({status:'success',tx_ref:p.tx_ref,already_verified:true})}const result=await verifyWithChapa(p);if(result.state==='success')return json({status:'success',tx_ref:p.tx_ref});if(result.state==='pending')return json({status:'pending',tx_ref:p.tx_ref},202);if(result.state==='failed')return json({status:'failed',tx_ref:p.tx_ref},402);if(result.state==='mismatch')return json({status:'failed',code:'VERIFICATION_MISMATCH',checks:result.checks},409);return json({status:'pending',tx_ref:p.tx_ref},202)}catch(e:any){console.error('chapa-verify',e);return json({code:e?.code,error:e instanceof Error?e.message:'Unexpected error'},e?.status||500)}});
