const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Content-Type':'application/json'};
const json=(d:unknown,s=200)=>new Response(JSON.stringify(d),{status:s,headers:cors});
function decodeJwt(t:string){const p=t.split('.')[1];if(!p)throw Object.assign(new Error('Invalid session'),{status:401});const n=p.replace(/-/g,'+').replace(/_/g,'/');return JSON.parse(atob(n.padEnd(Math.ceil(n.length/4)*4,'=')))}
async function rest(path:string,init:RequestInit={}){const u=Deno.env.get('SUPABASE_URL')!,k=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const h=new Headers(init.headers||{});h.set('apikey',k);h.set('Authorization',`Bearer ${k}`);if(init.body)h.set('Content-Type','application/json');const r=await fetch(`${u}/rest/v1/${path}`,{...init,headers:h});const tx=await r.text();let d:any=null;try{d=tx?JSON.parse(tx):null}catch{d=tx}if(!r.ok)throw Object.assign(new Error(typeof d==='object'?(d?.message||d?.hint||`Database ${r.status}`):`Database ${r.status}`),{status:500});return d}
async function feature(key:string){return (await rest('rpc/platform_feature_available',{method:'POST',body:JSON.stringify({p_feature_key:key})}))===true}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({error:'Method not allowed'},405);try{
 if(!(await feature('payments')))return json({code:'PAYMENTS_DISABLED',error:'Mela subscription checkout is not enabled yet.'},503);
 const token=(req.headers.get('Authorization')||'').replace(/^Bearer\s+/i,'');const c=decodeJwt(token),uid=String(c.sub||''),email=String(c.email||'');if(!uid||!email)return json({error:'Authenticated user identity is incomplete'},401);
 const body=await req.json().catch(()=>({}));const productKey=String(body?.product_key||'').trim();if(!productKey)return json({error:'product_key is required'},400);
 const rows=await rest(`mela_learning_products?select=*&product_key=eq.${encodeURIComponent(productKey)}&active=eq.true&limit=1`),p=rows?.[0];if(!p)return json({error:'Learning product not found'},404);
 if(!p.sale_enabled||!p.active_price_minor||Number(p.active_price_minor)<=0)return json({code:'NOT_FOR_SALE',error:'This learning product is not enabled for checkout.'},409);
 if(!['subscription','one_time'].includes(String(p.product_type)))return json({error:'Product type is not eligible for public checkout'},400);
 const prof=(await rest(`profiles?select=full_name,education_stage_key&id=eq.${uid}&limit=1`))?.[0]||{};const stages=Array.isArray(p.audience_stage_keys)?p.audience_stage_keys:[];if(stages.length&&(!prof.education_stage_key||!stages.includes(prof.education_stage_key)))return json({code:'AUDIENCE_MISMATCH',error:'This product is not available for your education stage.'},403);
 if(p.product_type==='one_time'){const e=await rest(`mela_user_learning_entitlements?select=id&user_id=eq.${uid}&product_key=eq.${encodeURIComponent(productKey)}&status=eq.active&limit=1`);if(e?.length)return json({code:'ALREADY_ENTITLED',error:'You already have this learning pack.'},409)}
 const ago=new Date(Date.now()-5*60*1000).toISOString();const recent=await rest(`mela_learning_payment_attempts?select=id&user_id=eq.${uid}&product_key=eq.${encodeURIComponent(productKey)}&status=in.(initiated,pending)&created_at=gte.${encodeURIComponent(ago)}&limit=3`);if((recent?.length||0)>=3)return json({code:'RATE_LIMITED',error:'Too many recent payment attempts. Verify an existing checkout or try later.'},429);
 const key=Deno.env.get('CHAPA_SECRET_KEY');if(!key)return json({code:'CHAPA_NOT_CONFIGURED',error:'Chapa test secret is not configured.'},503);if(!/TEST/i.test(key))return json({code:'CHAPA_TEST_KEY_REQUIRED',error:'Pre-launch learning checkout accepts only a Chapa TEST secret.'},503);
 const full=String(prof.full_name||'Mela Learner').trim(),parts=full.split(/\s+/).filter(Boolean),first=parts[0]||'Mela',last=parts.slice(1).join(' ')||'Learner';const txRef=`mela_learning_test_${Date.now()}_${crypto.randomUUID().replaceAll('-','').slice(0,12)}`;const amount=(Number(p.active_price_minor)/100).toFixed(2),currency=String(p.currency||'ETB').toUpperCase();
 const supa=Deno.env.get('SUPABASE_URL')!,callbackUrl=`${supa}/functions/v1/mela-learning-payment-callback`,returnBase=String(Deno.env.get('MELA_RETURN_URL')||'').replace(/\/$/,'');const returnUrl=returnBase?`${returnBase}?learning_payment=return&tx_ref=${encodeURIComponent(txRef)}`:undefined;
 const ins=await rest('mela_learning_payment_attempts?select=id',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({user_id:uid,product_key:productKey,mode:'test',tx_ref:txRef,expected_amount_minor:Number(p.active_price_minor),expected_currency:currency,status:'initiated'})});const payId=ins?.[0]?.id;if(!payId)throw new Error('Payment attempt could not be created');
 const payload:any={amount,currency,email,first_name:first,last_name:last,tx_ref:txRef,callback_url:callbackUrl,customization:{title:`Mela — ${p.product_name}`,description:'Mela learning access — TEST payment'},meta:{product_key:productKey,phase:'phase1'}};if(returnUrl)payload.return_url=returnUrl;
 const cr=await fetch('https://api.chapa.co/v1/transaction/initialize',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify(payload)});const txt=await cr.text();let ch:any={};try{ch=txt?JSON.parse(txt):{}}catch{}const checkout=ch?.data?.checkout_url;if(!cr.ok||!checkout){await rest(`mela_learning_payment_attempts?id=eq.${payId}`,{method:'PATCH',body:JSON.stringify({status:'failed',failure_reason:ch?.message||`Chapa initialize ${cr.status}`})});return json({code:'CHAPA_INITIALIZE_FAILED',error:ch?.message||'Unable to initialize Chapa checkout.'},502)}
 await rest(`mela_learning_payment_attempts?id=eq.${payId}`,{method:'PATCH',body:JSON.stringify({status:'pending',checkout_url:checkout,provider_status:ch?.status||'success',updated_at:new Date().toISOString()})});return json({checkout_url:checkout,tx_ref:txRef,mode:'test',product:{product_key:productKey,name:p.product_name,amount,currency}})
}catch(e:any){console.error('mela-learning-checkout',e);return json({error:e instanceof Error?e.message:'Unexpected error'},e?.status||500)}});
