import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'content-type, chapa-signature, x-chapa-signature','Access-Control-Allow-Methods':'POST, OPTIONS','Content-Type':'application/json'};
const json=(d:unknown,s=200)=>new Response(JSON.stringify(d),{status:s,headers:cors});
async function rest(path:string,init:RequestInit={}){const u=Deno.env.get('SUPABASE_URL')!,k=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const h=new Headers(init.headers||{});h.set('apikey',k);h.set('Authorization',`Bearer ${k}`);if(init.body)h.set('Content-Type','application/json');const r=await fetch(`${u}/rest/v1/${path}`,{...init,headers:h});const tx=await r.text();let d:any=null;try{d=tx?JSON.parse(tx):null}catch{d=tx}if(!r.ok)throw new Error(typeof d==='object'?(d?.message||d?.hint||`Database error ${r.status}`):`Database error ${r.status}`);return d}
function paymentMode(){return Deno.env.get('MELA_PAYMENT_MODE')==='live'?'live':'test'}
function key(){const k=Deno.env.get('CHAPA_SECRET_KEY');if(!k)throw new Error('CHAPA_SECRET_KEY is not configured');return k}
async function hmac(secret:string,msg:string){const e=new TextEncoder();const k=await crypto.subtle.importKey('raw',e.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const sig=new Uint8Array(await crypto.subtle.sign('HMAC',k,e.encode(msg)));return Array.from(sig).map(x=>x.toString(16).padStart(2,'0')).join('')}
function eq(a:string,b:string){if(a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a.charCodeAt(i)^b.charCodeAt(i);return x===0}
async function verifySignature(req:Request,raw:string){const sec=Deno.env.get('CHAPA_WEBHOOK_SECRET');if(!sec)return {ok:false,reason:'CHAPA_WEBHOOK_SECRET is not configured'};const x=(req.headers.get('x-chapa-signature')||'').trim().toLowerCase();const c=(req.headers.get('chapa-signature')||'').trim().toLowerCase();const ex=await hmac(sec,raw);return {ok:!!((x&&eq(x,ex))||(c&&eq(c,ex))),reason:'Invalid Chapa webhook signature'}}
async function notify(user_id:string,title:string,body:string,ref_id:string){try{await rest('notifications',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({user_id,title,body,ref_table:'escrow_transactions',ref_id})})}catch(e){console.error('notify',e)}}
async function verifyAttempt(p:any){const r=await fetch(`https://api.chapa.co/v1/transaction/verify/${encodeURIComponent(p.tx_ref)}`,{headers:{Authorization:`Bearer ${key()}`}});const tx=await r.text();let b:any={};try{b=tx?JSON.parse(tx):{}}catch{}const now=new Date().toISOString();if(!r.ok){await rest(`escrow_payment_attempts?id=eq.${p.id}`,{method:'PATCH',body:JSON.stringify({status:r.status===404?'pending':p.status,provider_status:b?.status||'pending',failure_reason:b?.message||`Chapa verify HTTP ${r.status}`,last_verified_at:now})});return {state:r.status===404?'pending':'error'}}const d=b?.data||{};const ps=String(d.status||'').toLowerCase();if(ps!=='success'){const mapped=ps==='failed'?'failed':'pending';await rest(`escrow_payment_attempts?id=eq.${p.id}`,{method:'PATCH',body:JSON.stringify({status:mapped,provider_status:ps||mapped,verify_payload:b,failure_reason:mapped==='failed'?(b?.message||'Payment failed'):null,last_verified_at:now})});return {state:mapped}}
const minor=Math.round(Number(d.amount)*100);const okRef=String(d.tx_ref||'')===p.tx_ref,okAmount=Number.isFinite(minor)&&minor===Number(p.expected_amount_minor),okCurrency=String(d.currency||'').toUpperCase()===String(p.currency||'').toUpperCase(),okMode=paymentMode()==='live'||String(d.mode||'').toLowerCase()==='test';if(!(okRef&&okAmount&&okCurrency&&okMode)){await rest(`escrow_payment_attempts?id=eq.${p.id}`,{method:'PATCH',body:JSON.stringify({status:'failed',provider_status:ps,verify_payload:b,failure_reason:`Verification mismatch ref=${okRef} amount=${okAmount} currency=${okCurrency} mode=${okMode}`,last_verified_at:now})});return {state:'mismatch'}}
const out=await rest('rpc/finalize_escrow_payment',{method:'POST',body:JSON.stringify({p_payment_id:p.id,p_provider_ref:d.reference||d.ref_id||null,p_provider_method:d.method||null,p_provider_type:d.type||null,p_provider_charge:minor,p_verify_payload:b})});
if(out?.idempotent!==true){const es=(await rest(`escrow_transactions?id=eq.${encodeURIComponent(out?.escrow_id||p.escrow_id)}&select=id,user_id&limit=1`))?.[0];if(es)await notify(es.user_id,'Escrow funded','The employer funded escrow for your freelance milestone.',es.id)}
return {state:'success',result:out}}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({error:'Method not allowed'},405);try{const raw=await req.text();const sig=await verifySignature(req,raw);if(!sig.ok)return json({error:sig.reason},sig.reason.includes('not configured')?503:401);let payload:any={};try{payload=raw?JSON.parse(raw):{}}catch{return json({error:'Invalid JSON'},400)}const ref=String(payload?.tx_ref||payload?.trx_ref||payload?.data?.tx_ref||payload?.data?.trx_ref||'');if(!ref)return json({error:'Webhook did not include tx_ref'},400);const p=(await rest(`escrow_payment_attempts?tx_ref=eq.${encodeURIComponent(ref)}&select=*&limit=1`))?.[0];if(!p)return json({received:true,tx_ref:ref,status:'not_escrow'},200);if(p.status==='success')return json({received:true,tx_ref:ref,status:'success',already_verified:true},200);const result=await verifyAttempt(p);return json({received:true,tx_ref:ref,status:result.state},200)}catch(e){console.error('mela-finance-callback',e);return json({error:e instanceof Error?e.message:'Unexpected error'},500)}});

